theme: jekyll-theme-architect
title: Welcome to my page!
description: This is the webpage of Pol Massana, currently a PGR at the University of Surrey. My main focus is the study of stellar populations of the Magellanic Clouds through the use of Colour-Magnitude diagrams.
